apiVersion: v1
kind: Service
metadata:
  name: command-response-mapper-service
spec:
  selector:
    app: command-response-mapper
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-response-mapper
spec:
  selector:
    matchLabels:
      app: command-response-mapper
  replicas: 2
  template:
    metadata:
      labels:
        app: command-response-mapper
    spec:
      containers:
        - name: command-response-mapper
          image: command-response-mapper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
