package za.co.mixtelematics.model;

public enum SedaApiRequests {
    GET_ALL_FLOW_STATUS,
    GET_SINGLE_FLOW_STATUS,
    GET_SINGLE_FLOW_AND_FOLDER_STATUS,

    GET_ALL_FLOW_EVENT_STATUS,
    GET_SINGLE_FLOW_EVENT_STATUS,
    GET_SINGLE_FLOW_AND_FOLDER_EVENT_STATUS,

    GET_ALL_EVENT_CONFIGURATION,
    GET_SINGLE_FLOW_EVENT_CONFIGURATION,
    GET_SINGLE_FLOW_AND_FOLDER_EVENT_CONFIGURATION,

    GET_THE_ASYNCHRONOUS_PROCESSES,
    GET_ALL_CONFIGURATION,
    GET_SMS_CONFIGURATION,
    GET_EMAIL_CONFIGURATION,

    RESET_STATUS_ON_ALL_FLOWS,
    RESET_STATUS_ON_SINGLE_FLOW,
    RESET_EVENT_STATUS_ON_ALL_FLOWS,
    RESET_EVENT_STATUS_ON_SINGLE_FLOW,
    RESET_EVENT_STATUS_ON_SINGLE_FLOW_AND_FOLDER,

    DELETE_ALL_FLOWS_EVENTS,
    DELETE_SINGLE_FLOW_EVENT,
    DELETE_SINGLE_FLOW_AND_FOLDER_EVENT,
    DELETE_THE_ASYNCHRONOUS_PROCESSES,
    DELETE_ALL_CONFIGURATION,
    DELETE_SMS_CONFIGURATION,
    DELETE_EMAIL_CONFIGURATION,

    ADD_EVENT_CONFIGURATION,

    UPDATE_EVENT_CONFIGURATION,
    UPDATE_SMS_CONFIGURATION,
    UPDATE_EMAIL_CONFIGURATION,


    CREATE_A_MOVE_ASYNCHRONOUS_PROCESS,
    CREATE_A_DELETE_ASYNCHRONOUS_PROCESS,
    CREATE_AND_MOVE_FILE,
    READ_FILE_CONTENTS,
    DELETE_FILE,
    MOVE_FILE,

    INVALID;
}
